name: tabular
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.4
  - pip
  - pip:
      - black==22.8.0
      - catboost==1.0.6
      - category-encoders==2.5.1.post0
      - fastparquet==2022.12.0
      - flake8==5.0.4
      - isort==5.11.4
      - jupyter==1.0.0
      - lightgbm==3.3.2
      - matplotlib==3.5.3
      - numpy==1.23.2
      - optuna==3.0.2
      - pandas==1.5.2
      - plotly==5.10.0
      - prettytable==3.6.0
      - pyarrow==10.0.1
      - pytorch-tabnet
      - scikit-learn==1.1.2
      - seaborn==0.11.2
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.64.1
      - wandb==0.13.2
      - xgboost==1.6.2
