task_type: binary
params:
  task_type: GPU
  learning_rate: 0.02
  l2_leaf_reg: 0.3
  bagging_temperature: 1
  min_data_in_leaf: 57
  max_bin: 494
  od_type: Iter
  od_wait: 500
  iterations: 10000
  allow_writing_files: False
multi_task: True
path: res/models/
working: catboost
results: 10fold-catboost-results.pkl
n_splits: 10
early_stopping_rounds: 100
search: False
seed: 42
verbose_eval: 100
