task_type: binary
n_splits: 10
path: res/models/
working: tabnet
results: tabnet-results
params:
  lr: 0.02
  step_size: 50
  gamma: 1.5
  n_d: 16
  n_steps: 5
  n_a: 16
  lambda_sparse: 0.0001
  max_epochs: 1000
  patience: 20
  batch_size: 4096
  virtual_batch_size: 128
  num_workers: 1
  mask_type: entmax
  verbose: 10
  seed: 0
eval_name:
  - train
  - valid
eval_metric:
  - logloss
