n_splits: 10
path: res/models/
working: tabnet
results: 10fold-tabnet-results.pkl
multi_task: True
params:
  lr: 0.002
  step_size: 50
  gamma: 1.2
  n_d: 32
  n_steps: 5
  n_a: 32
  lambda_sparse: 0.001
  max_epochs: 1000
  patience: 10
  batch_size: 4096
  virtual_batch_size: 512
  num_workers: 1
  mask_type: entmax
  verbose: 10
